Repository software-mansion/react-native-audio-api, pull requests merged in 2025-06, with the labels that each got.

#472 docs: added info note about plugin
  packages/audiodocs/docs/fundamentals/getting-started.mdx
  packages/audiodocs/docs/other/audio-api-plugin.mdx
  packages/audiodocs/docs/other/web-audio-api-coverage.mdx
  packages/react-native-audio-api/src/plugin/withAudioAPI.ts
Labels: documentation

#486 feat: implemented decoding pcm in base64
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioDecoder.h
  packages/react-native-audio-api/common/cpp/audioapi/libs/base64/base64.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioDecoder.mm
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#491 Cant wait to do that - PAUSE in RN-Audio-API
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferQueueSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
  packages/react-native-audio-api/src/events/types.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#492 fix: fixed stop
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
  packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
Labels: fix

#501 Docs/few line pages integration
  packages/audiodocs/docs/core/audio-context.mdx
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/types/audio-buffer-source-node-options.mdx
  packages/audiodocs/docs/types/audio-context-options.mdx
  packages/audiodocs/docs/types/context-state.mdx
  packages/audiodocs/docs/types/periodic-wave-constraints.mdx
  packages/audiodocs/src/css/colors.css
Labels: documentation

#504 Refactor/audio buffer base source node
  .github/pull_request_template.md
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/common-app/src/examples/AudioFile/AudioPlayer.ts
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferBaseSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferQueueSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferBaseSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferBaseSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
  packages/react-native-audio-api/src/core/AudioBufferBaseSourceNode.ts
  packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
  packages/react-native-audio-api/src/core/AudioBufferSourceNode.ts
  packages/react-native-audio-api/src/core/AudioScheduledSourceNode.ts
  packages/react-native-audio-api/src/events/types.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/web-core/AudioScheduledSourceNode.tsx
Labels: refactoring, breaking-change

#469 Enable Native External Audio Processing via TurboModules
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/CustomProcessorNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.h
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/core/CustomProcessorNode.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/types.ts
Labels: development, high priority

#513 fix: iOS restart engine after AVAudioSessionMediaServicesWereResetNot…
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
Labels: fix

#514 fix: fixed lock screen skip commands for android above 12
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/common-app/src/examples/AudioFile/AudioPlayer.ts
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.h
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/core/CustomProcessorNode.ts
  packages/react-native-audio-api/src/types.ts
Labels: fix

#521 docs: updated compatibility table and web audio mapi coverage
  apps/common-app/src/examples/AudioFile/AudioPlayer.ts
  packages/audiodocs/docs/other/compatibility.mdx
  packages/audiodocs/docs/other/web-audio-api-coverage.mdx
Labels: documentation

#524 chore: released 0.6.3
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/package.json
Labels: chore

#528 docs: updated compatibility table
  packages/audiodocs/docs/other/compatibility.mdx
Labels: documentation

#531 fix: fixed typo
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.cpp
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
Labels: fix
