Repository software-mansion/react-native-audio-api, pull requests merged in 2025-09, with the labels that each got.

#617 [blocked] chore: dropped support for RN 0.75
  packages/audiodocs/docs/other/compatibility.mdx
  packages/react-native-audio-api/android/build.gradle
  packages/react-native-audio-api/android/src/main/cpp/audioapi/CMakeLists.txt
Labels: chore, breaking-change

#643 fix: change type to void
  packages/audiodocs/docs/sources/streamer-node.mdx
  packages/react-native-audio-api/src/core/AudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: fix

#639 feat: audio param performance improvement
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioParamHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParamEventQueue.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParamEventQueue.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/ParamChangeEvent.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/ParamChangeEvent.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/CrossThreadEventScheduler.hpp
  packages/react-native-audio-api/common/cpp/audioapi/utils/RingBiDirectionalBuffer.hpp
Labels: improvement

#646 fix: proper recording stopping
  apps/common-app/src/examples/Record/Record.tsx
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
Labels: fix

#644 Fix/android foreground service
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/fabric-example/android/app/src/main/AndroidManifest.xml
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.h
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/NativeAudioPlayer.hpp
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/core/NativeAudioPlayer.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaReceiver.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/android/src/main/res/drawable/logo.xml
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioContextHostObject.h
  packages/react-native-audio-api/src/plugin/withAudioAPI.ts
Labels: fix

#647 refactor: license updated
  COPYING
  README.md
  THIRD_PARTY.md
  lgplv3
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/StreamerNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/StreamerNode.h
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.cpp
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.h
Labels: documentation

#648 docs: small update to compatibility table
  packages/audiodocs/docs/other/compatibility.mdx
Labels: documentation

#652 fix: number of channels
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.cpp
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioDecoder.mm
Labels: fix

#655 fix: change paths resolving in ffmpeg libraries
  packages/react-native-audio-api/common/cpp/audioapi/external/libavcodec.xcframework/ios-arm64/libavcodec.framework/libavcodec
  packages/react-native-audio-api/common/cpp/audioapi/external/libavcodec.xcframework/ios-arm64_x86_64-simulator/libavcodec.framework/libavcodec
  packages/react-native-audio-api/common/cpp/audioapi/external/libavformat.xcframework/Info.plist
  packages/react-native-audio-api/common/cpp/audioapi/external/libavformat.xcframework/ios-arm64/libavformat.framework/libavformat
  packages/react-native-audio-api/common/cpp/audioapi/external/libavformat.xcframework/ios-arm64_x86_64-simulator/libavformat.framework/libavformat
  packages/react-native-audio-api/common/cpp/audioapi/external/libavutil.xcframework/ios-arm64/libavutil.framework/libavutil
  packages/react-native-audio-api/common/cpp/audioapi/external/libavutil.xcframework/ios-arm64_x86_64-simulator/libavutil.framework/libavutil
  packages/react-native-audio-api/common/cpp/audioapi/external/libswresample.xcframework/Info.plist
  packages/react-native-audio-api/common/cpp/audioapi/external/libswresample.xcframework/ios-arm64/libswresample.framework/libswresample
  packages/react-native-audio-api/common/cpp/audioapi/external/libswresample.xcframework/ios-arm64_x86_64-simulator/libswresample.framework/libswresample
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/create_xcframework.sh
  packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/ffmpeg_setup.sh
Labels: fix

#656 docs: improvements
  packages/audiodocs/docs/core/audio-context.mdx
  packages/audiodocs/docs/core/audio-param.mdx
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
  packages/audiodocs/docs/sources/audio-buffer.mdx
  packages/audiodocs/docs/sources/audio-scheduled-source-node.mdx
  packages/audiodocs/docs/sources/oscillator-node.mdx
  packages/audiodocs/docs/sources/streamer-node.mdx
Labels: documentation

#651 Docs: interactive playgrounds
  packages/audiodocs/docs/effects/gain-node.mdx
  packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
  packages/audiodocs/docs/sources/oscillator-node.mdx
  packages/audiodocs/docusaurus.config.js
  packages/audiodocs/package.json
  packages/audiodocs/src/components/InteractivePlayground/AudioBufferSourceExample/AudioBufferSourceExample.tsx
  packages/audiodocs/src/components/InteractivePlayground/AudioBufferSourceExample/useAudioBufferSourcePlayground.tsx
  packages/audiodocs/src/components/InteractivePlayground/GainAdsrExample/AdsrChart.tsx
  packages/audiodocs/src/components/InteractivePlayground/GainAdsrExample/GainAdsrExample.tsx
  packages/audiodocs/src/components/InteractivePlayground/GainAdsrExample/constants.ts
  packages/audiodocs/src/components/InteractivePlayground/GainAdsrExample/useGainAdsrPlayground.tsx
  packages/audiodocs/src/components/InteractivePlayground/OscillatorExample/OscillatorExample.tsx
  packages/audiodocs/src/components/InteractivePlayground/OscillatorExample/useOscilatorPlayground.tsx
  packages/audiodocs/src/components/InteractivePlayground/WaveformVisualizer.tsx
  packages/audiodocs/src/components/InteractivePlayground/index.tsx
  packages/audiodocs/src/components/InteractivePlayground/interactivePlaygroundMuiTheme.tsx
  packages/audiodocs/src/components/InteractivePlayground/styles.module.css
  packages/audiodocs/src/wasm-loader.js
  packages/audiodocs/static/signalsmithStretch.mjs
Labels: documentation

#672 fix: added bin to package.json
  packages/custom-node-generator/bin/cli.js
  packages/custom-node-generator/package.json
Labels: fix

#685 Docs improvements
  packages/audiodocs/docs/core/audio-context.mdx
  packages/audiodocs/docs/core/audio-param.mdx
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/core/offline-audio-context.mdx
  packages/audiodocs/docs/effects/gain-node.mdx
  packages/audiodocs/docs/effects/periodic-wave.mdx
  packages/audiodocs/docs/inputs/audio-recorder.mdx
  packages/audiodocs/docs/sources/audio-buffer-queue-source-node.mdx
  packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
  packages/audiodocs/docs/sources/oscillator-node.mdx
Labels: documentation

#625 [unblocked] feat: worklets support
  .yarn/releases/yarn-4.5.0.cjs
  apps/common-app/package.json
  apps/common-app/src/examples/Worklets/Worklets.tsx
  apps/common-app/src/examples/index.ts
  apps/fabric-example/ios/Podfile.lock
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/worklets/introduction.mdx
  packages/audiodocs/docs/worklets/worklet-node.mdx
  packages/react-native-audio-api/RNAudioAPI.podspec
  packages/react-native-audio-api/android/build.gradle
  packages/react-native-audio-api/android/src/main/cpp/audioapi/CMakeLists.txt
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.h
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.h
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/WorkletNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/WorkletNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/WorkletNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/worklets/SafeIncludes.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/worklets/UiWorkletsRunner.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/worklets/UiWorkletsRunner.h
  packages/react-native-audio-api/common/cpp/audioapi/jsi/AudioArrayBuffer.h
  packages/react-native-audio-api/common/cpp/test/CMakeLists.txt
  packages/react-native-audio-api/common/cpp/test/GainTest.cpp
  packages/react-native-audio-api/common/cpp/test/OscillatorTest.cpp
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/package.json
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/core/WorkletNode.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/utils/index.ts
  yarn.lock
Labels: feature

#691 feat(android): support background recording
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.h
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/NativeAudioRecorder.hpp
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/core/NativeAudioRecorder.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
Labels: feature

#695 feat: new example file
  packages/audiodocs/static/audio/other/mixed-channels.opus
Labels: documentation

#702 Chore/removed worklets workaround
  packages/audiodocs/docs/worklets/worklet-node.mdx
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
Labels: chore
