Repository software-mansion/react-native-audio-api, pull requests merged in 2025-07, with the labels that each got.

#541 fix: show algolia search on not landing - landing page
  .github/workflows/publish-docs.yml
  packages/audiodocs/docusaurus.config.js
  packages/audiodocs/package.json
  packages/audiodocs/patches/@swmansion+t-rex-ui+1.0.0.patch
  packages/audiodocs/yarn.lock
Labels: documentation, fix

#549 docs: updated docs fro onEnded and extracted decoding method
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/sources/audio-buffer.mdx
  packages/audiodocs/docs/sources/audio-scheduled-source-node.mdx
Labels: documentation

#555 test: refactor tests
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp
  packages/react-native-audio-api/common/cpp/test/CMakeLists.txt
Labels: tests

#564 Refactor/new ff and rewind 15 s icons
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/res/drawable/skip_backward_10.xml
  packages/react-native-audio-api/android/src/main/res/drawable/skip_backward_15.xml
  packages/react-native-audio-api/android/src/main/res/drawable/skip_forward_10.xml
  packages/react-native-audio-api/android/src/main/res/drawable/skip_forward_15.xml
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
Labels: feature, breaking-change

#546 feat: introduced playback speed manipulation to decode base64 with pcm
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioDecoder.h
  packages/react-native-audio-api/common/cpp/audioapi/libs/audio-stretch/stretch.c
  packages/react-native-audio-api/common/cpp/audioapi/libs/audio-stretch/stretch.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioDecoder.mm
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature, breaking-change

#568 fix: fixed package json version
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/package.json
Labels: chore

#572 Refactor/biquad filter node
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/effects/biquad-filter-node.mdx
  packages/audiodocs/docs/effects/gain-node.mdx
  packages/audiodocs/docs/effects/stereo-panner-node.mdx
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/StereoPannerNode.cpp
Labels: documentation, feature, refactoring

#573 docs: examples for various decoding
  packages/audiodocs/docs/core/base-audio-context.mdx
Labels: documentation

#569 Feat/recorder adapter node
  apps/common-app/src/examples/Record/Record.tsx
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/inputs/audio-recorder.mdx
  packages/audiodocs/docs/sources/recorder-adapter-node.mdx
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioRecorderHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/RecorderAdapterNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/RecorderAdapterNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/RecorderAdapterNode.h
  packages/react-native-audio-api/common/cpp/audioapi/jsi/AudioArrayBuffer.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/CircularOverflowableAudioArray.cpp
  packages/react-native-audio-api/common/cpp/audioapi/utils/CircularOverflowableAudioArray.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/AudioRecorder.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/core/RecorderAdapterNode.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#562 new setup for custom processor
  README.md
  packages/audiodocs/docs/guides/create-your-own-effect.mdx
  packages/audiodocs/docs/guides/see-your-sound.mdx
  packages/audiodocs/docusaurus.config.js
  packages/custom-node-generator/README.md
  packages/custom-node-generator/bin/cli.js
  packages/custom-node-generator/lib/generator.js
  packages/custom-node-generator/package-lock.json
  packages/custom-node-generator/package.json
  packages/custom-node-generator/templates/basic/shared/MyProcessorNode.cpp
  packages/custom-node-generator/templates/basic/shared/MyProcessorNode.h
  packages/custom-node-generator/templates/basic/shared/MyProcessorNodeHostObject.h
  packages/custom-node-generator/templates/basic/shared/NativeAudioProcessingModule.cpp
  packages/custom-node-generator/templates/basic/shared/NativeAudioProcessingModule.h
  packages/custom-node-generator/templates/basic/specs/NativeAudioProcessingModule.ts
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioNodeHostObject.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/CustomProcessorNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.h
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/core/CustomProcessorNode.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: documentation, feature, development

#578 Audio Context/Recorder lifecycle improvements
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  packages/audiodocs/docs/system/audio-manager.mdx
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.h
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/android/src/oldarch/NativeAudioAPIModuleSpec.java
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.cpp
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/src/core/AudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/specs/NativeAudioAPIModule.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
Labels: documentation, refactoring, fix
