Repository software-mansion/react-native-audio-api, pull requests merged in 2025-03, with the labels that each got.

#360 fix: added missing async-await RNAA-22
  packages/audiodocs/src/examples/LetsMakeSomeNoise/Component.tsx
  packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseComponent.tsx
  packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseComponent.tsx
  packages/audiodocs/src/examples/NoiseGeneration/WhiteNoiseComponent.tsx
  packages/audiodocs/src/examples/SeeYourSound/BaseComponent.tsx
  packages/audiodocs/src/examples/SeeYourSound/FrequencyDomainComponent.tsx
  packages/audiodocs/src/examples/SeeYourSound/TimeDomainComponent.tsx
  packages/audiodocs/src/examples/SimplePiano/EnvelopesComponent.tsx
  packages/audiodocs/src/examples/SimplePiano/FinalComponent.tsx
  packages/audiodocs/src/examples/SimplePiano/ItHangsComponent.tsx
  packages/audiodocs/src/examples/SimplePiano/PressOutComponent.tsx
  packages/audiodocs/yarn.lock
Labels: bug

#367 Fix/audio buffer deallocation
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/PeriodicWave.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.cpp
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.h
Labels: fix

#373 Refactor/absn and stretcher
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBuffer.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBuffer.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/AudioArray.cpp
  packages/react-native-audio-api/common/cpp/audioapi/utils/AudioArray.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/AudioBus.cpp
  packages/react-native-audio-api/common/cpp/audioapi/utils/AudioBus.h
Labels: fix

#375 Fix/buffer locking and small nitpicks
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
Labels: fix

#376 Memory management improvements
  apps/common-app/src/examples/AudioVisualizer/AudioVisualizer.tsx
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  apps/common-app/src/examples/DrumMachine/constants.ts
  apps/common-app/src/utils/usePlayer.tsx
  apps/fabric-example/ios/FabricExample.xcodeproj/project.pbxproj
  apps/fabric-example/ios/FabricExample/Info.plist
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/.clang-format
  packages/react-native-audio-api/.eslintrc.js
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AnalyserNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioParamHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/PeriodicWave.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/PeriodicWave.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/StretcherNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/StretcherNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.mm
Labels: bug, fix

#378 Fix/memory manage improvements
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  apps/common-app/src/examples/DrumMachine/constants.ts
  apps/common-app/src/utils/usePlayer.tsx
  packages/react-native-audio-api/.clang-format
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/PeriodicWave.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.mm
Labels: fix

#380 Fix/disconnect node
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
Labels: fix
