Repository software-mansion/react-native-audio-api, pull requests merged in 2025-04, with the labels that each got.

#387 fix: delayed start
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
Labels: fix

#389 feat/Offline Audio Context
  apps/common-app/src/examples/OfflineRendering/OfflineRendering.tsx
  apps/common-app/src/examples/OfflineRendering/index.ts
  apps/common-app/src/examples/index.ts
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/OfflineAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.h
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/api.web.ts
  packages/react-native-audio-api/src/core/OfflineAudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/types.ts
  packages/react-native-audio-api/src/web-core/OfflineAudioContext.tsx
Labels: feature

#390 Fix/try call with lock
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeDestructor.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeDestructor.h
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
Labels: fix

#391 fix: fixed resultBus_ initializing, it should happen after sampleRate
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp
Labels: fix

#392 chore: released 0.5.6
  apps/fabric-example/ios/Podfile.lock
  packages/audiodocs/package.json
  packages/react-native-audio-api/package.json
Labels: chore

#371 Audio controls IOS
  .gitattributes
  apps/fabric-example/ios/FabricExample.xcodeproj/project.pbxproj
  apps/fabric-example/ios/FabricExample/Info.plist
  apps/fabric-example/ios/Podfile.lock
  apps/fabric-example/tsconfig.json
  packages/react-native-audio-api/RNAudioAPI.podspec
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.h
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIPackage.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
  packages/react-native-audio-api/android/src/oldarch/NativeAudioManagerModuleSpec.java
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/AudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/package.json
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/AudioContext.ts
  packages/react-native-audio-api/src/specs/NativeAudioManagerModule.ts
  packages/react-native-audio-api/src/specs/index.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
  packages/react-native-audio-api/src/system/index.ts
  packages/react-native-audio-api/src/system/types.ts
Labels: feature

#393 Feat/android/audio controls
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/fabric-example/android/app/src/main/AndroidManifest.xml
  packages/react-native-audio-api/android/CMakeLists.txt
  packages/react-native-audio-api/android/build.gradle
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaReceiver.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionEventEmitter.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/android/src/main/res/drawable/next.xml
  packages/react-native-audio-api/android/src/main/res/drawable/pause.xml
  packages/react-native-audio-api/android/src/main/res/drawable/play.xml
  packages/react-native-audio-api/android/src/main/res/drawable/previous.xml
  packages/react-native-audio-api/android/src/main/res/drawable/skip_backward_5.xml
  packages/react-native-audio-api/android/src/main/res/drawable/skip_forward_5.xml
  packages/react-native-audio-api/android/src/main/res/drawable/stop.xml
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/src/specs/NativeAudioManagerModule.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
  packages/react-native-audio-api/src/system/types.ts
Labels: feature, development

#398 Refactor/audio manager module
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaReceiver.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionEventEmitter.kt
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/src/system/AudioManager.ts
  packages/react-native-audio-api/src/system/types.ts
Labels: refactoring

#407 fix: fixed event name typo
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
Labels: fix

#406 Chore/cmake cxx flags
  packages/react-native-audio-api/android/CMakeLists.txt
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeDestructor.cpp
Labels: chore

#408 fix: onended callback calling twice
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
Labels: fix

#409 chore: released 0.6.0-rc.1
  apps/fabric-example/ios/FabricExample.xcodeproj/project.pbxproj
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/package.json
Labels: chore

#396 Audio Recorder Node
  apps/common-app/src/examples/Record/Record.tsx
  apps/common-app/src/examples/index.ts
  apps/fabric-example/ios/FabricExample.xcodeproj/project.pbxproj
  apps/fabric-example/ios/FabricExample/Info.plist
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AnalyserNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioRecorderHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeIOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeIOSAudioRecorder.m
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/package.json
  packages/react-native-audio-api/scripts/create-package.sh
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/AudioRecorder.ts
  packages/react-native-audio-api/src/errors/NotSupportedError.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/specs/NativeAudioManagerModule.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
  packages/react-native-audio-api/src/system/types.ts
  packages/react-native-audio-api/src/types.ts
Labels: feature, unstable

#411 Feat/android/audio recorder
  apps/fabric-example/android/app/src/main/AndroidManifest.xml
  apps/fabric-example/android/app/src/main/java/com/fabricexample/MainActivity.kt
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.h
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/src/plugin/withAudioAPI.ts
Labels: feature

#413 Fix/audio-engine
  .github/actions/spelling/allow.txt
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.h
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioPlayer.h
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioRecorderHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioPlayer.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.h
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeIOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeIOSAudioRecorder.m
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/src/types.ts
Labels: fix

#418 Release/0.6.0 rc.2
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/package.json
Labels: chore

#422 Fix/analyser node/wrong offset while copying
  packages/react-native-audio-api/common/cpp/audioapi/core/analysis/AnalyserNode.cpp
Labels: fix

#423 feat: added custom buffer length on iOS
  apps/common-app/src/examples/Record/Record.tsx
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
Labels: feature

#424 chore: released 0.6.0-rc.4
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/package.json
Labels: chore

#426 docs: fix highlighted sections in lets-make-some-noise
  packages/audiodocs/docs/guides/lets-make-some-noise.mdx
Labels: fix

#425 Refactor/circular audio array
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/analysis/AnalyserNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/analysis/AnalyserNode.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/AudioArray.h
  packages/react-native-audio-api/common/cpp/audioapi/utils/CircularAudioArray.cpp
  packages/react-native-audio-api/common/cpp/audioapi/utils/CircularAudioArray.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
Labels: refactoring

#427 Release/0.6.0 rc.5
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/package.json
Labels: chore
