Repository software-mansion/react-native-audio-api, pull requests merged in 2025-08, with the labels that each got.

#584 fix: docpage links
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/effects/biquad-filter-node.mdx
  packages/audiodocs/docs/effects/stereo-panner-node.mdx
  packages/audiodocs/docs/guides/create-your-own-effect.mdx
  packages/audiodocs/docs/guides/see-your-sound.mdx
  packages/audiodocs/docs/inputs/audio-recorder.mdx
  packages/audiodocs/docs/sources/recorder-adapter-node.mdx
  packages/audiodocs/docs/system/audio-manager.mdx
Labels: fix

#591 chore: readme update
  README.md
Labels: chore

#590 feat: dequeue for AudioBufferQueueSourceNode
  packages/audiodocs/docs/sources/audio-buffer-queue-source-node.mdx
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferQueueSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
  packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#593 Feat/new examples
  apps/common-app/package.json
  apps/common-app/src/components/Select.tsx
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  apps/common-app/src/examples/PlaybackSpeed/PlaybackSpeed.tsx
  apps/common-app/src/examples/PlaybackSpeed/constants.ts
  apps/common-app/src/examples/PlaybackSpeed/helpers.ts
  apps/common-app/src/examples/PlaybackSpeed/index.ts
  apps/common-app/src/examples/PlaybackSpeed/types.ts
  apps/common-app/src/examples/index.ts
  apps/fabric-example/ios/Podfile.lock
  yarn.lock
Labels: feature

#600 fix: fix path to external libraries in podspec
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/RNAudioAPI.podspec
Labels: fix

#602 fix: recorder and audio context issue
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m
Labels: bug, fix

#599 fix: turned off JSI_DEBUG_ALLOCATIONS
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.cpp
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.h
Labels: fix

#605 fix: disconnecting all nodes in manager
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
Labels: fix

#619 Fix/biquad performance
  packages/audiodocs/docs/effects/biquad-filter-node.mdx
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.h
Labels: refactoring, fix

#627 Docs/biquad example
  apps/common-app/package.json
  apps/fabric-example/ios/Podfile.lock
  packages/audiodocs/.eslintrc
  packages/audiodocs/babel.config.js
  packages/audiodocs/docs/effects/biquad-filter-node.mdx
  packages/audiodocs/docs/guides/noise-generation.mdx
  packages/audiodocs/docusaurus.config.js
  packages/audiodocs/package.json
  packages/audiodocs/src/components/AudioApiExample/index.tsx
  packages/audiodocs/src/components/AudioApiExample/styles.module.css
  packages/audiodocs/src/examples/Biquad/BiquadExampleComponent.tsx
  packages/audiodocs/src/examples/Biquad/BoxWithFlaps.tsx
  packages/audiodocs/src/examples/Biquad/FrequencyResponseGraph.tsx
  packages/audiodocs/src/examples/Biquad/RangeSlider.tsx
  packages/audiodocs/src/examples/Biquad/drawFrequencyResponse.tsx
  packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseComponent.tsx
  packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseSource.tsx
  packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseComponent.tsx
  packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseSource.tsx
  packages/audiodocs/static/img/gramophone.png
  packages/audiodocs/yarn.lock
  yarn.lock
Labels: documentation

#622 Docs/periodic wave
  packages/audiodocs/docs/analysis/analyser-node.mdx
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/effects/gain-node.mdx
  packages/audiodocs/docs/effects/periodic-wave.mdx
  packages/audiodocs/docs/effects/stereo-panner-node.mdx
  packages/audiodocs/docs/sources/audio-buffer-queue-source-node.mdx
  packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
  packages/audiodocs/docs/sources/oscillator-node.mdx
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
Labels: documentation, fix

#632 chore: bumped up skia and example app clean up
  apps/common-app/package.json
  apps/common-app/src/examples/AudioVisualizer/Canvas.tsx
  apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
  apps/common-app/src/examples/DrumMachine/PlayButton.tsx
  apps/common-app/src/examples/TextToSpeech/TextToSpeech.tsx
  apps/common-app/src/examples/TextToSpeech/index.ts
  apps/common-app/src/examples/index.ts
  apps/common-app/src/utils/env.ts
  apps/fabric-example/babel.config.js
  apps/fabric-example/ios/Podfile.lock
  yarn.lock
Labels: chore
