Repository software-mansion/react-native-audio-api, pull requests merged in 2025-05, with the labels that each got.

#431 Fix/get rid of singletons and refactor modules
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIPackage.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
  packages/react-native-audio-api/android/src/oldarch/NativeAudioAPIModuleSpec.java
  packages/react-native-audio-api/android/src/oldarch/NativeAudioManagerModuleSpec.java
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
  packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/specs/NativeAudioAPIModule.ts
  packages/react-native-audio-api/src/specs/NativeAudioManagerModule.ts
  packages/react-native-audio-api/src/specs/index.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
Labels: refactoring

#440 fix: get rid of round that caused frequency to be always int
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
Labels: bug

#438 fix: fixed reject wrapper in jsi promise
  packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp
Labels: bug

#432 feat: added logic for connecting node to param
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioParamHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.h
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/BiquadFilterNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/GainNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/effects/StereoPannerNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h
  packages/react-native-audio-api/src/core/AudioBufferSourceNode.ts
  packages/react-native-audio-api/src/core/AudioNode.ts
  packages/react-native-audio-api/src/core/AudioParam.ts
  packages/react-native-audio-api/src/core/BiquadFilterNode.ts
  packages/react-native-audio-api/src/core/GainNode.ts
  packages/react-native-audio-api/src/core/OscillatorNode.ts
  packages/react-native-audio-api/src/core/StereoPannerNode.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#439 Refactor/android/audio session manager
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaReceiver.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
Labels: refactoring

#433 Feat/audio event handler
  apps/common-app/src/examples/AudioFile/AudioFile.tsx
  apps/common-app/src/examples/Record/Record.tsx
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.h
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.h
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaNotificationManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaReceiver.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionEventEmitter.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
  packages/react-native-audio-api/common/cpp/audioapi/AudioAPIModuleInstaller.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioRecorderHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioScheduledSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/OscillatorNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/AudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
  packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
  packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.h
  packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistryHostObject.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.h
  packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/LockScreenManager.mm
  packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
  packages/react-native-audio-api/package.json
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/AudioRecorder.ts
  packages/react-native-audio-api/src/core/AudioScheduledSourceNode.ts
  packages/react-native-audio-api/src/events/AudioEventEmitter.ts
  packages/react-native-audio-api/src/events/AudioEventSubscription.ts
  packages/react-native-audio-api/src/events/index.ts
  packages/react-native-audio-api/src/events/types.ts
  packages/react-native-audio-api/src/hooks/useSytemVolume.ts
  packages/react-native-audio-api/src/interfaces.ts
  packages/react-native-audio-api/src/specs/NativeAudioAPIModule.ts
  packages/react-native-audio-api/src/specs/index.ts
  packages/react-native-audio-api/src/system/AudioManager.ts
  packages/react-native-audio-api/src/system/types.ts
  packages/react-native-audio-api/src/types.ts
  yarn.lock
Labels: feature

#437 Fix/android/audio recorder/missing last audio chunk
  packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AndroidAudioRecorder.cpp
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
  packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
  packages/react-native-audio-api/ios/audioapi/ios/events/IOSAudioEventHandlerRegistry.h
  packages/react-native-audio-api/ios/audioapi/ios/events/IOSAudioEventHandlerRegistry.mm
Labels: bug

#448 chore: released 0.6.0 and fixed merge changes
  apps/fabric-example/ios/Podfile.lock
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
  packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
  packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
  packages/react-native-audio-api/package.json
Labels: chore

#444 docs: stereo panner node
  packages/audiodocs/docs/core/base-audio-context.mdx
  packages/audiodocs/docs/effects/stereo-panner-node.mdx
Labels: documentation

#453 Feat/onended/added state to payload
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
  packages/react-native-audio-api/src/core/AudioScheduledSourceNode.ts
  packages/react-native-audio-api/src/events/types.ts
Labels: feature

#461 feat: naive approach to streaming in beloved cpp
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferQueueSourceNodeHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBuffer.h
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
  packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
  packages/react-native-audio-api/src/api.ts
  packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
  packages/react-native-audio-api/src/core/BaseAudioContext.ts
  packages/react-native-audio-api/src/interfaces.ts
Labels: feature

#460 docs: add mention about connecting node to param
  packages/audiodocs/docs/core/audio-node.mdx
Labels: documentation

#459 fix: added possibility of disconnection between node and param in ts
  packages/react-native-audio-api/src/core/AudioNode.ts
Labels: fix

#467 docs: added search bar into the documentation
  .github/workflows/publish-docs.yml
  packages/audiodocs/docusaurus.config.js
  packages/audiodocs/src/theme/Navbar/index.jsx
Labels: documentation

#458 Docs/audio manager
  packages/audiodocs/docs/system/_category_.json
  packages/audiodocs/docs/system/audio-manager.mdx
  packages/audiodocs/src/components/Badges/index.tsx
Labels: documentation
